# Generated by Django 2.2.15 on 2020-08-14 16:12

from django.db import migrations
import django_enumfield.db.fields
import xchk_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('xchk_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionv2',
            name='state',
            field=django_enumfield.db.fields.EnumField(default=3, enum=xchk_core.models.SubmissionState),
        ),
    ]
