# Generated by Django 2.2.15 on 2020-08-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchk_core', '0002_auto_20200814_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionv2',
            name='content_uid',
            field=models.CharField(max_length=200),
        ),
    ]
